import React from 'react';
import { Quotation } from '@/types/quotation';
import { format } from 'date-fns';

const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:0,maximumFractionDigits:0}).format(v);
function numberToWords(num:number){if(num===0)return'ZERO';const ones=['','ONE','TWO','THREE','FOUR','FIVE','SIX','SEVEN','EIGHT','NINE','TEN','ELEVEN','TWELVE','THIRTEEN','FOURTEEN','FIFTEEN','SIXTEEN','SEVENTEEN','EIGHTEEN','NINETEEN'],tens=['','','TWENTY','THIRTY','FORTY','FIFTY','SIXTY','SEVENTY','EIGHTY','NINETY'];const h=(n:number):string=>n<20?ones[n]:n<100?tens[Math.floor(n/10)]+(n%10?' '+ones[n%10]:''):ones[Math.floor(n/100)]+' HUNDRED'+(n%100?' '+h(n%100):'');let r='';const c=Math.floor(num/1e7),l=Math.floor(num%1e7/1e5),t=Math.floor(num%1e5/1e3),x=num%1e3;if(c)r+=h(c)+' CRORE ';if(l)r+=h(l)+' LAKH ';if(t)r+=h(t)+' THOUSAND ';if(x)r+=h(x);return r.trim()}
export function QuotationPDFTemplate({quotation}:{quotation:Quotation}){const items=quotation.items||[],total=Math.round(quotation.total||0);const terms=quotation.terms_and_conditions||'All disputes subject to Chandigarh jurisdiction only.\nInterest @18% per annum will be charged if bills are not paid within 15 days.\nGoods once sold will not be taken back.';return <div id="quotation-print-area" style={{fontFamily:'Arial,sans-serif',fontSize:12,color:'#1a1a1a',background:'#fff',padding:'30px 36px',maxWidth:800,margin:'0 auto',lineHeight:1.4,WebkitPrintColorAdjust:'exact',printColorAdjust:'exact'}}>
 <div style={{background:'#1a1a1a',color:'#fff',padding:'20px 24px',margin:'-30px -36px 16px',borderBottom:'3px solid #c8a96e'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:10,color:'#aaa'}}><span>GSTIN: 03AMVPT8346H1ZD</span><span>Phone: 7009234919</span></div><div style={{textAlign:'center',marginTop:6}}><h1 style={{fontSize:22,fontWeight:800,margin:'0 0 2px'}}>MAHARAJA MARBLE & GRANITES</h1><p style={{margin:0,color:'#ccc',fontSize:11}}>Plot No. 658, JLPL, Sector 82, Mohali, Punjab, India</p><p style={{margin:'2px 0 0',color:'#ccc',fontSize:11}}>Deals in: Quartz, Granite and Marble</p></div><div style={{textAlign:'right',fontSize:10,color:'#aaa',marginTop:4}}>Reverse Charges: No</div></div>
 <div style={{display:'flex',justifyContent:'space-between',borderBottom:'1px solid #e0e0e0',paddingBottom:10,marginBottom:14}}><div style={{background:'#c8a96e',color:'#fff',padding:'4px 14px',borderRadius:3,fontSize:11,fontWeight:600,letterSpacing:1}}>QUOTATION</div><div style={{textAlign:'right'}}><p style={{margin:0,fontSize:14,fontWeight:700}}>{quotation.quotation_number}</p><p style={{margin:'3px 0 0',fontSize:11,color:'#555'}}>Date: {format(new Date(quotation.quotation_date),'dd MMM yyyy')}</p>{quotation.valid_until&&<p style={{margin:'2px 0',fontSize:10,color:'#555'}}>Valid until: {format(new Date(quotation.valid_until),'dd MMM yyyy')}</p>}</div></div>
 <div style={{marginBottom:16}}><p style={{margin:'0 0 4px',fontSize:9,fontWeight:700,color:'#888',textTransform:'uppercase'}}>Bill To</p><p style={{margin:0,fontSize:14,fontWeight:700}}>{quotation.client_name}</p>{quotation.client_phone&&<p style={{margin:'2px 0',color:'#555',fontSize:11}}>{quotation.client_phone}</p>}{quotation.client_email&&<p style={{margin:'2px 0',color:'#555',fontSize:11}}>{quotation.client_email}</p>}{quotation.client_address&&<p style={{margin:'2px 0',color:'#555',fontSize:11}}>{quotation.client_address}</p>}</div>
 <table style={{width:'100%',borderCollapse:'collapse',marginBottom:20,fontSize:11}}><thead><tr style={{background:'#c8a96e'}}>{['SR.','HSN/SAC','ITEM','QTY','UNIT','RATE (₹)','AMOUNT (₹)'].map((h,i)=><th key={h} style={{padding:'8px 6px',textAlign:i===2?'left':i>4?'right':'center',fontWeight:600}}>{h}</th>)}</tr></thead><tbody>{items.map((item,i)=><tr key={item.id}><td style={{padding:8,textAlign:'center',borderBottom:'1px solid #e5e5e5'}}>{i+1}</td><td style={{padding:8,textAlign:'center',borderBottom:'1px solid #e5e5e5',color:'#777'}}>{(item as any).hsn_code||'6802'}</td><td style={{padding:'8px 10px',borderBottom:'1px solid #e5e5e5',fontWeight:600}}>{item.item_name}</td><td style={{padding:8,textAlign:'center',borderBottom:'1px solid #e5e5e5'}}>{item.quantity}</td><td style={{padding:8,textAlign:'center',borderBottom:'1px solid #e5e5e5'}}>{item.unit}</td><td style={{padding:8,textAlign:'right',borderBottom:'1px solid #e5e5e5'}}>{money(item.rate)}</td><td style={{padding:'8px 10px',textAlign:'right',borderBottom:'1px solid #e5e5e5',fontWeight:600}}>{money(item.amount)}</td></tr>)}</tbody></table>
 <div style={{display:'flex',justifyContent:'flex-end',marginBottom:16}}><div style={{width:260}}>{[['Subtotal',quotation.subtotal],['GST ('+quotation.gst_percentage+'%)',quotation.gst_amount],['Freight / Cartage',(quotation as any).freight_amount||0]].map(([label,value])=><div key={String(label)} style={{display:'flex',justifyContent:'space-between',padding:'5px 0',borderBottom:'1px solid #e5e5e5'}}><span style={{color:'#555'}}>{label}</span><span style={{fontWeight:600}}>{money(Number(value))}</span></div>)}<div style={{display:'flex',justifyContent:'space-between',padding:'10px 12px',background:'#c8a96e',borderRadius:4,marginTop:4,fontWeight:800}}><span>GRAND TOTAL</span><span>{money(total)}</span></div></div></div>
 <div style={{background:'#fffdf7',border:'1px solid #e8d5a3',borderLeft:'3px solid #c8a96e',padding:'8px 12px',marginBottom:16}}><b style={{fontSize:10}}>AMOUNT IN WORDS: </b><span style={{fontSize:11,fontWeight:600}}>{numberToWords(total)} ONLY</span></div>
 {quotation.notes&&<div style={{marginBottom:16,padding:12,background:'#f5f5f5',borderLeft:'3px solid #1a1a1a'}}><b style={{fontSize:10}}>NOTES</b><p style={{margin:'4px 0 0',whiteSpace:'pre-wrap',fontSize:11,color:'#444'}}>{quotation.notes}</p></div>}
 <div style={{marginBottom:20}}><p style={{margin:'0 0 6px',fontSize:10,fontWeight:700,color:'#c8a96e',textTransform:'uppercase'}}>Terms & Conditions</p><div style={{fontSize:10,color:'#555',lineHeight:1.8,whiteSpace:'pre-wrap'}}>{terms}</div></div>
 <div style={{borderTop:'2px solid #c8a96e',paddingTop:12}}><div style={{textAlign:'center',fontSize:10,color:'#c8a96e',marginBottom:16,fontWeight:700}}>Our Bank: Canara Bank | A/C No. 120001351990 | IFSC: CNRB0019620</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end'}}><div><p style={{margin:0,fontSize:10,color:'#888'}}>Prepared by: {quotation.assigned_to}</p><p style={{margin:'4px 0 0',fontSize:10,color:'#888'}}>Thank you for your business!</p><div style={{marginTop:24,borderTop:'1px solid #aaa',paddingTop:4,width:120,fontSize:10,textAlign:'center'}}>Received By</div></div><div style={{textAlign:'right'}}><p style={{margin:0,fontSize:11,fontWeight:700}}>Maharaja Marble & Granites</p><div style={{marginTop:24,borderTop:'1px solid #aaa',paddingTop:4,fontSize:10,textAlign:'center'}}>Authorised Signature</div></div></div></div>
 </div>}
