ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS closed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS reschedule_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reschedule_reason TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS reminder_offset_hours INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS custom_reminder_at TIMESTAMPTZ DEFAULT NULL;